<?php

/**
 * @file
 */


/**
 * Implements hook_field_attach_view_alter().
 *
 * Use this hook to make sure it works when using the body field in views and
 * panels, without the need to add anything else.
 */
function ywp_write_field_attach_view_alter(&$output, $context) {
  if ($context['entity_type'] == 'node' && $context['entity']->type == 'challenge') {
    $node = $context['entity'];
    $css = drupal_get_path('module', 'ywp_write') . '/css/write.css';

    $write_link_options = array(
      'query' => array('field_challenge' => $node->nid),
      'attributes' => array('title' => t('click this to create a post for this challenge')),
      'html' => TRUE,
    );
    $write_link = l('<button type="button">' . t('write') . '</button>', 'node/add/blog', $write_link_options);
    $more_link = l(t('More Challenges'), 'challenges');
    $text = '<div class="ywp-write"><p class="ywp-write-button">' . $write_link . '</p><span>' . $more_link . '</span></div>';

    $output['body'][0]['#markup'] .= $text;
    $output['body'][0]['#attached']['css'][] = $css;
  }
}

/**
 * Implements hook_node_view().
 */
function ywp_write_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'blog') {
    $node->content['links']['blog']['#links']['ywp_write'] = array(
      'title' => t('Sprout'),
      'href' => 'node/add/blog',
      'query' => array(
        'field_ywp_sprout' => $node->nid,
      ),
      'attributes' => array(),
    );
  }


  return $node;
}

